(ns ren-finance.main
  (:require [cljd.flutter :as f]
            ["package:flutter/material.dart" :as material]
            [ren-finance.model.subs :as subs]
            [re-dash.core :as rd]))

(defn app []
  (f/widget (material/MaterialApp
              .title "Ren Finance"
              .theme (material/ThemeData .useMaterial3 true)
              .home (material/Text "Hello from Ren Finance!"))))

(defn main []
  (f/run (app)))
